### ISSUE TITLE
s2i assemble script fails due to exceeding github API rate limit

### ISSUE THREAD

**Issue by juanvallejo** [aweiteka/playbook2image#29]
Assemble script fails while parsing the [OC_BINARY_URL](https://github.com/aweiteka/playbook2image/blob/master/.s2i/bin/assemble#L38) due to hitting API rate limit:

```
$ python -c "import requests;print [s for s in [r for r in requests.get('https://api.github.com/repos/openshift/origin/releases').json() if not r['prerelease'] and '1.4' in r['name']][0]['assets'] if 'linux-64' in s['browser_download_url']][0]['browser_download_url']"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: string indices must be integers
```

If we run just the part that returns the json response:
```
$ python -c "import requests;requests.get('https://api.github.com/repos/openshift/origin/releases').json()"

{u'documentation_url': u'https://developer.github.com/v3/#rate-limiting',
 u'message': u"API rate limit exceeded for 66.187.233.202. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"}
```

**Comment by aweiteka** [comment]
We need to support unauthenticated requests, which I validated are limited to [60 requests per hour](https://developer.github.com/v3/#rate-limiting) per IP address.

@jcpowermac the logic you implemented here is slick. The user doesn't have to know about a specific release. I'd like to retain that. Do you think we could do less looping or maybe maintain a hard-coded link to a specific release?

@codificat how have you modified the assemble script to install oc via RPM?

**Comment by jcpowermac** [comment]
@aweiteka I didn't know that API had a limit ... let me figure out a fix.

**Comment by codificat** [comment]
In a Dockerfile that builds upon playbook2image and is RPM-based the idea is to *not* invoke the `assemble` script at build time. In that type of Dockerfile everything is installed from packages, and dependencies would not be an exception. For example, the `Dockerfile.rhel7` for the `openshift-ansible` image (PR still pending) would `yum install openshift-ansible-playbooks` to get the "source" in, and it would also install `atomic-openshift-clients` at the same time to pull in `oc`.

I'll submit a PR with changes to the example `Dockerfile.advanced` and associated doc to explain that.

**Comment by aweiteka** [comment]
@juanvallejo issue #30 should resolve this. New base image has been pushed to registry,  docker.io/aweiteka/playbook2image.
