### ISSUE TITLE
Fix travis builds

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/playbook2image#7]
Travis is failing due to missing test script dependencies in the Ubuntu-based build VM.
https://travis-ci.org/aweiteka/playbook2image

**Comment by aweiteka** [comment]
We need to get this working to avoid broken commits that have slipped in.

**Comment by jcpowermac** [comment]
@aweiteka I forced a build and getting this error.
https://travis-ci.org/aweiteka/playbook2image/builds/205892867#L9159

On my local machine the error is past the creation of the docker image in the s2i testing.
```
Testing 's2i usage'...
cp: cannot create regular file '/src/tmp_inventory': Permission denied
S2I image 'playbook2image-candidate' test FAILED (exit code: 1)
Untagged: playbook2image-candidate-testapp:latest
```

**Comment by aweiteka** [comment]
ACK. I haven't had a chance to look at this. Not sure which commit broke it.
